<?php
    echo '<div class="title">';
    echo 'API สำหรับจำแนกเมนูอาหารด้วยปริมาณแคลอรี่ และวัตถุดิบ';
    echo '</div>';
    echo '<div class="subtitle">';
    echo 'ค้นหาด้วยช่วงของปริมาณแคลอรี่ หรือวัตถุดิบ';
    echo '</div>'; 
    echo '<p> url: http://api.foodapi.icu/api/advance-search/</p>';
    echo '<p> การเรียกใช้ API ทำการเรียกใช้โดยรูปแบบ POST โดยมีข้อมูลที่ต้องส่งผ่าน url ดังนี้</p>';
    echo '<table style="width:100%">';
    echo '<tr>';
    echo '<th>ตัวแปร</th>';
    echo '<th>ความจำเป็น</th>';
    echo '<th>ชนิดตัวแปร</th>';
    echo '<th>คำอธิบาย</th>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>username</td>';
    echo '<td>ใช่</td>';
    echo '<td>string</td>';
    echo '<td>ไอดีผู้ใข้ของผู้ใช้งาน API</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>api_key</td>';
    echo '<td>ใช่</td>';
    echo '<td>string</td>';
    echo '<td>รหัสในการเรียกใช้ API ที่ผูกกับบัญชีผู้ใช้</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>skip</td>';
    echo '<td>ไม่</td>';
    echo '<td>int</td>';
    echo '<td>จำนวนข้อมูลที่ต้องการข้าม</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>limit</td>';
    echo '<td>ไม่</td>';
    echo '<td>int</td>';
    echo '<td>จำนวนข้อมูลที่ต้องการได้รับ</td>';
    echo '</tr>';
    echo '</table>';
    echo '<br><p> ส่วนข้อมูลที่ต้องส่งไปในรูปแบบ Json มีดังนี้ </p>';
    echo '<table style="width:100%">';
    echo '<tr>';
    echo '<th>ตัวแปร</th>';
    echo '<th>ความจำเป็น</th>';
    echo '<th>ชนิดตัวแปร</th>';
    echo '<th>คำอธิบาย</th>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>mincal</td>';
    echo '<td>ใช่</td>';
    echo '<td>float</td>';
    echo '<td>ช่วงปริมาณแคลอรี่ต่ำสุดของเมนูอาหาร</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>maxcal</td>';
    echo '<td>ใช่</td>';
    echo '<td>float</td>';
    echo '<td>ช่วงปริมาณแคลอรี่สูงสุดของเมนูอาหาร</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>minchol</td>';
    echo '<td>ใช่</td>';
    echo '<td>float</td>';
    echo '<td>ช่วงปริมาณคอเลสเตอรอลต่ำสุดของเมนูอาหาร</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>maxchol</td>';
    echo '<td>ใช่</td>';
    echo '<td>float</td>';
    echo '<td>ช่วงปริมาณคอเลสเตอรอลสูงสุดของเมนูอาหาร</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>mincarb</td>';
    echo '<td>ใช่</td>';
    echo '<td>float</td>';
    echo '<td>ช่วงปริมาณคาร์โบไฮเดรตต่ำสุดของเมนูอาหาร</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>maxcarb</td>';
    echo '<td>ใช่</td>';
    echo '<td>float</td>';
    echo '<td>ช่วงปริมาณคาร์โบไฮเดรตสูงสุดของเมนูอาหาร</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>minfat</td>';
    echo '<td>ใช่</td>';
    echo '<td>float</td>';
    echo '<td>ช่วงปริมาณไขมันต่ำสุดของเมนูอาหาร</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>maxfat</td>';
    echo '<td>ใช่</td>';
    echo '<td>float</td>';
    echo '<td>ช่วงปริมาณไขมันสูงสุดของเมนูอาหาร</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>minprotein</td>';
    echo '<td>ใช่</td>';
    echo '<td>float</td>';
    echo '<td>ช่วงปริมาณโปรตีนต่ำสุดของเมนูอาหาร</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>maxprotein</td>';
    echo '<td>ใช่</td>';
    echo '<td>float</td>';
    echo '<td>ช่วงปริมาณโปรตีนสูงสุดของเมนูอาหาร</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>name</td>';
    echo '<td>ไม่</td>';
    echo '<td>array of string</td>';
    echo '<td>ชื่อวัตถุดิบที่ต้องการในเมนูอาหาร</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>exname</td>';
    echo '<td>ไม่</td>';
    echo '<td>array of string</td>';
    echo '<td>ชื่อวัตถุดิบที่ไม่ต้องการในเมนูอาหาร</td>';
    echo '</tr>';
    echo '</table>';
    echo '<br><p> ตัวอย่างการเรียกใช้งาน </p>';
    echo '<p> &nbsp&nbsp&nbsp&nbsp- ข้อมูลที่ส่งผ่าน url</p>';
    echo '<div class="example">';
    echo '/api/menu-detail/ingre-name?username=cheasel&api_key=a8b8529fd9f1897c0fd4cc7c2140d1415242fd64cb4def0df94e42ae77c7ebb5&skip=0&limit=20';
    echo '</div>';
    echo '<p> <br>&nbsp&nbsp&nbsp&nbsp- ข้อมูลที่ส่งในรูปแบบ Json</p>';
    echo '<div class="example">';
    echo '<p>{</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"mincal": 100,</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"maxcal": 400,</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"minchol": 100,</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"maxchol": 400,</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"mincarb": 100,</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"maxcarb": 400,</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"minfat": 100,</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"maxfat": 400,</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"minprotein": 100,</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"maxprotein": 400,</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"name": [</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"หมู"</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp],</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"exname": [</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"ไก่"</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp]</p>';
    echo '<p>}</p>';
    echo '</div>';
    echo '<br><p> ตัวอย่างข้อมูลที่ได้ </p>';
    echo '<div class="data">';
    echo '<p>{</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"_id": 11,</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"user": "",</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"title": "หมูทอด คลาสสิค",</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"serve": 1,</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"ingredients": [</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"name": "หมูเนื้อแดง",</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"value": "350",</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"unit": "กรัม"</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp},</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"name": "น้ำมันหอย",</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"value": "20",</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"unit": "มล"</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp},</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"name": "ผงกระเทียม",</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"value": "2",</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"unit": "กรัม"</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp},</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"name": "พริกไทยขาวป่น",</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"value": "1",</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"unit": "กรัม"</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp},</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"name": "น้ำตาลทราย",</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"value": "1",</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"unit": "กรัม"</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp},</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"name": "ซีอิ๊วดำ",</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"value": "1",</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"unit": "มล"</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp},</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"name": "น้ำมันพืชสำหรับทอด",</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"value": "1",</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"unit": ""</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp}</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp],</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"preparations": [</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"หั่นหมูเนื้อแดงเป็นชิ้น",</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"ใส่น้ำมันหอย ซีอิ๊วดำ น้ำตาล ผงกระเทียม พริกไทยขาวป่น เพื่อหมักหมู หมักอย่างน้อย 2 ชั่วโมง",</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"ตั้งกระทะไฟปานกลางใส่น้ำมัน พอน้ำมันร้อนให้ลดไฟ และนำหมูลงทอด",</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"หมูทอดเสร็จละจ้าหุงข้าวเหนียวร้อนๆ กินคู่กันนน ฟินนนน"</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp],</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"image": "https://img.wongnai.com/p/1968x0/2020/09/07/d7140c94c3234c38ae5d15a81b535913.jpg",</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"reference": "https://www.wongnai.com/recipes/ugc/7b9ac2dcbf0d4a64b8bda6539ae75ba5",</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"nutrition": {</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"calories": {</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"quantity": 305.4165091363267,</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"unit": "kcal"</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp},</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"carbohydrates": {</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"quantity": 2.658593720954652,</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"unit": "g"</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp},</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"cholesterol": {</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"quantity": 220.5,</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"unit": "mg"</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp},</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"fat": {</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"quantity": 44.090865240864346,</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"unit": "g"</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp},</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"protein": {</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"quantity": 69.41867230066747,</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"unit": "g"</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp}</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp},</p>';
    echo '<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"description": "Work From Home เลยอดซื้อข้าวเหนียวหมูทอดเจ้าประจำ งั้นทำกินเองเลยละกัน "</p>';
    echo '<p>}</p>';
    echo '</div>';
?>